SELECT SUM(B.POPULATION)
FROM (SELECT CODE FROM COUNTRY WHERE CONTINENT = 'ASIA') AS A JOIN CITY B ON A.CODE = B.COUNTRYCODE

#SOLUTION2
SELECT SUM(CITY.POPULATION) 
FROM CITY, COUNTRY
WHERE CITY.COUNTRYCODE = COUNTRY.CODE AND COUNTRY.CONTINENT = 'Asia';