SELECT DISTINCT(A.N), IF(A.P IS NULL,'Root',
     IF(B.P IS NULL,'Leaf','Inner'))
FROM BST A LEFT JOIN BST B ON A.N = B.P
ORDER BY A.N

#SOLUTION 2
SELECT N, IF(P IS NULL,'Root',IF((SELECT COUNT(*) FROM BST WHERE P=B.N)>0,'Inner','Leaf')) FROM BST AS B ORDER BY N;