SELECT H.HACKER_ID, NAME, TOTAL_SCORE
FROM 
    (SELECT HACKER_ID, SUM(SCORE) AS TOTAL_SCORE
    FROM 
        (SELECT H.HACKER_ID, S.CHALLENGE_ID, MAX(SCORE) AS SCORE
        FROM HACKERS H, SUBMISSIONS S
        WHERE H.HACKER_ID = S.HACKER_ID
        GROUP BY H.HACKER_ID, S.CHALLENGE_ID) AS SCORE_TABLE
    GROUP BY HACKER_ID
    HAVING SUM(SCORE) <> 0) AS TOTAL_SCORE_TABLE, HACKERS H
WHERE TOTAL_SCORE_TABLE.HACKER_ID = H.HACKER_ID
ORDER BY TOTAL_SCORE DESC, H.HACKER_ID