SELECT DISTINCT(C.COMPANY_CODE), C.FOUNDER, 
(SELECT COUNT(DISTINCT(LEAD_MANAGER_CODE)) FROM LEAD_MANAGER WHERE C.COMPANY_CODE = LEAD_MANAGER.COMPANY_CODE),
(SELECT COUNT(DISTINCT(SENIOR_MANAGER_CODE)) FROM SENIOR_MANAGER WHERE C.COMPANY_CODE = SENIOR_MANAGER.COMPANY_CODE),
(SELECT COUNT(DISTINCT(MANAGER_CODE)) FROM MANAGER WHERE C.COMPANY_CODE = MANAGER.COMPANY_CODE),
(SELECT COUNT(DISTINCT(EMPLOYEE_CODE)) FROM EMPLOYEE WHERE C.COMPANY_CODE = EMPLOYEE.COMPANY_CODE) 
FROM COMPANY AS C
ORDER BY C.COMPANY_CODE