SELECT T1.NAME
FROM 
(SELECT S.ID, S.NAME,P.SALARY
FROM STUDENTS S JOIN PACKAGES P ON S.ID = P.ID) AS T1,
(SELECT S.ID, S.NAME,P.SALARY
FROM STUDENTS S JOIN PACKAGES P ON S.ID = P.ID) AS T2,
(SELECT S.ID,S.NAME,FRIEND_ID
FROM STUDENTS S JOIN FRIENDS F ON S.ID = F.ID) AS T3
WHERE T3.ID = T1.ID AND T3.FRIEND_ID = T2.ID AND T1.SALARY < T2.SALARY
ORDER BY T2.SALARY

# Solution 2
SELECT s.Name FROM Students AS s 
JOIN Packages AS sp ON s.ID = sp.ID 
JOIN Friends AS f ON s.ID = f.ID
JOIN Packages AS fp ON f.Friend_ID = fp.ID
WHERE sp.Salary < fp.Salary
ORDER BY fp.Salary;
