SELECT CEIL(AVG(A.SALARY) - AVG(B.SALARY))
FROM EMPLOYEES A, (SELECT REPLACE(SALARY,'0','') AS SALARY FROM EMPLOYEES) AS B

#Solution2
SELECT CEIL(AVG(SALARY)-AVG(REPLACE(SALARY,"0",""))) FROM EMPLOYEES