# ';' 을 잊지말자

SELECT S.NAME, G.GRADE, S.MARKS
FROM STUDENTS S, GRADES G 
WHERE S.MARKS >= G.MIN_MARK AND S.MARKS <= G.MAX_MARK AND  G.GRADE >= 8
ORDER BY G.GRADE DESC, S.NAME;

SELECT NULL,G.GRADE,S.MARKS
FROM STUDENTS S, GRADES G
WHERE S.MARKS >= G.MIN_MARK AND S.MARKS <= G.MAX_MARK AND G.GRADE < 8
ORDER BY G.GRADE DESC, S.MARKS