SELECT CITY, LENGTH(CITY)
FROM STATION A, (SELECT MAX(LENGTH(CITY)) AS MAX_LEN FROM STATION) AS TEMP_TABLE
WHERE LENGTH(A.CITY) = TEMP_TABLE.MAX_LEN
ORDER BY CITY LIMIT 1 OFFSET 0;

SELECT CITY, LENGTH(CITY)
FROM STATION A, (SELECT MIN(LENGTH(CITY)) AS MIN_LEN FROM STATION) AS TEMP_TABLE
WHERE LENGTH(A.CITY) = TEMP_TABLE.MIN_LEN
ORDER BY CITY LIMIT 1 OFFSET 0

#MORE SIMPLE SOLUTION (여러개의 정렬조건 이용)
SELECT CITY, length(CITY) FROM STATION ORDER BY length(CITY) DESC, CITY ASC limit 1;
SELECT CITY, length(CITY) FROM STATION ORDER BY length(CITY) ASC, CITY ASC limit 1;